# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-Camellia_PP
version:      0.01
version_from: lib/Crypt/Camellia_PP.pm
installdirs:  site
requires:
    Crypt::CBC:                    2.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
